### ISSUE TITLE
Error: can't call function init

### ISSUE THREAD

**Issue by RepeZero** [tuarua/Firebase-ANE#39]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1
0.6.0

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?
Samsung S8+

- **With which operating system?**
    - iOS 11, Android 7 etc?
Android 9

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?
Win10

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
Animate

- **Which version of AIR are you using?**
    - 29, 30.. etc?
33.0.2.246

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
setting ANE, import all ANE in fla, code at timeline-script : var auth:AuthANE=AuthANE.auth;

- **What is the expected output? What do you see instead?**

Error: can't call function init
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua.firebase::AuthANE()[/Users/eoinlandy/flash/Firebase-ANE/native_extension/AuthANE/src/com/tuarua/firebase/AuthANE.as:14]
	at com.tuarua.firebase::AuthANE$/get auth()[/Users/eoinlandy/flash/Firebase-ANE/native_extension/AuthANE/src/com/tuarua/firebase/AuthANE.as:25]
	at FireBaseANETest_fla::MainTimeline/frame1()[FireBaseANETest_fla.MainTimeline::frame1:9]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.
Stack trace in debug mode :
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91)
	at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
	at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:141)
	at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1174)
	at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1453)
	at com.adobe.air.AndroidActivityWrapper$1.run(AndroidActivityWrapper.java:1435)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalStateException: FirebaseAuth.getInstance(app) must not be null
	at com.tuarua.firebase.auth.AuthController.<init>(AuthController.kt:41)
	at com.tuarua.firebase.auth.KotlinController.init(KotlinController.kt:35)
	... 14 more

- **Does this problem also occur in the Sample Application provided?**

**Comment by tuarua** [comment]
This happens when you don't configure _your app.xml_ correctly.
Make sure you follow the instructions on the wiki correctly.

https://github.com/tuarua/Firebase-ANE/wiki/Analytics---Configuring-the-ANE
https://github.com/tuarua/Firebase-ANE/wiki/Authentication---Configuring-the-ANE

https://github.com/tuarua/Firebase-ANE/blob/master/example/src/Main-app-android.xml

**Comment by RepeZero** [comment]
Thanks! I add 
<meta-data
        android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
            android:value="com.google.firebase.components.ComponentRegistrar" />
at my app.xml! Thanks add it on wiki!
